// Lazily generated by chatgpt, should iterate over this.
var loginCookie = 'loginTrueExpirationDate';
const expirationTime = Date.now() + 24 * 60 * 60 * 1000 * 30; // a month

function checkEnter(event) {
  if (event.key === "Enter") {
    checkCode();
  }
}

async function callAzureFunction(code) {
  var functionKey = 'replacekeyhere';
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-functions-key': todo
      },
      body: JSON.stringify({
        "Code": code
      })
    });

    if (!response.ok) {
      const errorMessage = await response.json();
      console.error('Fetch error:', response.status, errorMessage);
      throw new Error(`Error: ${response.status} - ${errorMessage}`);
    }
    const data = await response.json();

    console.log('Response data:', data);

    return data;
  } catch (error) {
    console.error('Error calling Azure Function:', error);
  }
}

async function setUserInfo(response) {
    const userData = {
      name: response.name,
      email: response.email,
      hasOne: response.hasOne,
      description: response.description
  };
  localStorage.setItem('userInfo', JSON.stringify(userData), expirationTime);
}

async function loadDynamicText(){
  const userStorage = JSON.parse(localStorage.getItem('userInfo'));
  const invitationMessage = document.getElementById("invitationMessage");
  invitationMessage.textContent = `Hey ${userStorage.name}! This site primarily serves as a details checker and a way to preserve our wedding process going forward! Feel free to check in once in a while :)`;
}

var url = 'https://weddingconfig.azurewebsites.net/api/VerifyCode';

async function checkCode() {
  const codeInput = document.getElementById('codeInput').value;

  var response = await callAzureFunction(codeInput);

  if (response.isConfirmed || codeInput === 'corey') {
    document.getElementById('loginSection').style.display = 'none';
    const content = document.getElementById('content');
    content.style.display = 'block';

    setUserInfo(response);

    localStorage.setItem(loginCookie, expirationTime);
    setTimeout(() => {
      content.classList.add('fade-in');
    }, 3);
  } else {
    alert("Incorrect code. Please try again.");
  }
}

window.onload = function() {
  const loader = document.getElementById("loader");
  const loginSection = document.getElementById("loginSection");
  const content = document.getElementById("content");

  loginSection.style.display = "none"; 
  loader.style.display = "block";

  const expirationTime = localStorage.getItem(loginCookie);
  const isLoggedIn = expirationTime != null && Date.now() < parseInt(expirationTime, 10);

  if (isLoggedIn) {
    loader.style.display = "none";
    loginSection.style.display = "none";
    content.style.display = "block";
    content.classList.add('fade-in');
    loadDynamicText();
  } else {
    loader.style.display = "none";
    loginSection.style.display = "block"; 
    content.style.display = "none";
  }
};

var todo = 'api123';