

// Lazily generated by chatgpt, should iterate over this.
function checkEnter(event) {
    if (event.key === "Enter") {
        checkCode();
    }
}

function checkCode() {
    const apiKey = 'GSHEETS_API_KEY';
    console.log(apiKey);
    const correctCode = "abc"; // Replace with the actual code
    const userCode = document.getElementById('codeInput').value;

    if (userCode === correctCode) {
        document.getElementById('loginSection').style.display = 'none';
        const content = document.getElementById('content');
        content.style.display = 'block'; // Make the content visible
        setTimeout(() => {
            content.classList.add('fade-in'); // Apply the fade-in effect
        }, 10); // Small delay to ensure display change is processed before adding the class
    } else {
        alert("Incorrect code. Please try again.");
    }
}

