// Lazily generated by chatgpt, should iterate over this.
var loginCookie = 'loginTrueExpirationDate';
const expirationTime = Date.now() + 24 * 60 * 60 * 1000 * 30; // a month

function checkEnter(event) {
  if (event.key === "Enter") {
    checkCode();
  }
}

async function callAzureFunction(code) {
  var functionKey = 'replacekeyhere';
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-functions-key': todo
      },
      body: JSON.stringify({
        "Code": code
      })
    });

    if (!response.ok) {
      const errorMessage = await response.json();
      console.error('Fetch error:', response.status, errorMessage);
      throw new Error(`Error: ${response.status} - ${errorMessage}`);
    }
    const data = await response.json();

    return data;
  } catch (error) {
    console.error('Error calling Azure Function:', error);
  }
}

async function setUserInfo(response) {
    const userData = {
      name: response.name,
      email: response.email,
      hasOne: response.hasOne,
      description: response.description,
      hasCeremony: response.hasCeremony,
      hasReception: response.hasReception,
  };
  localStorage.setItem('userInfo', JSON.stringify(userData), expirationTime);
}

async function loadDynamicText(){
  const userStorage = JSON.parse(localStorage.getItem('userInfo'));
  const invitationMessage = document.getElementById("invitationMessage");
  invitationMessage.textContent = `Hey ${userStorage.name}! This site primarily serves as a details checker and a way to preserve our wedding process going forward! Feel free to check in once in a while :)`;
  loadRSVP(userStorage);
  loadCeremony(userStorage);
  loadVenues(userStorage);
  loadParking(userStorage);
  loadWelcomeDialog(userStorage);
}

function loadWelcomeDialog(userStorage) {
  const welcomeButtonContent = document.getElementById("welcome-button-content");
  if (userStorage.description !== ""){
    const welcomeDialog = document.getElementById("welcome-modal-body");
    welcomeDialog.textContent = `${userStorage.description}`;
    if (!localStorage.getItem('welcomeModalShown')) {
      $('#welcome-modal').modal('show');

      localStorage.setItem('welcomeModalShown', 'true');
    }
  }
  welcomeButtonContent.style.display = userStorage.description === "" ? 'none' : 'block';
}

function loadRSVP(userStorage){
  const plusOneBox = document.getElementById("plus-one");
  const eventOptionBox = document.getElementById("event-option");
  const eventSelect = eventOptionBox.querySelector('select');
  plusOneBox.style.display = userStorage.hasOne ? 'block' : 'none';
  eventOptionBox.style.display = userStorage.hasCeremony ? 'block' : 'none';
  eventSelect.value = userStorage.hasCeremony ? "" : "reception";
}

function loadCeremony(userStorage){
  const ceremonyContent = document.getElementById("ceremony-content");
  const ceremonyDressCode = document.getElementById("ceremony-dress-code");
  const ceremonyVenue = document.getElementById("ceremony-venue");
  ceremonyContent.style.display = userStorage.hasCeremony ? 'block' : 'none';
  ceremonyDressCode.style.display = userStorage.hasCeremony ? 'block' : 'none';
  ceremonyVenue.style.display = userStorage.hasCeremony ? 'block' : 'none';
}

function loadVenues(userStorage){
  const venueTitle = document.getElementById("venue-title");
  const venueRestaurant = document.getElementById("venue-restaurant");
  venueTitle.textContent = userStorage.hasCeremony ? "VENUES" : "VENUE";
  venueRestaurant.className = userStorage.hasCeremony ? "col-md-6 venue-rightcol" : "venue-container";
}

function loadParking(userStorage){
  const ceremonyRestaurant = document.getElementById("ceremony-parking");
  ceremonyRestaurant.style.display = userStorage.hasCeremony ? 'block' : 'none';
}

var url = 'https://weddingconfig.azurewebsites.net/api/VerifyCode';

async function checkCode() {
  const codeInput = document.getElementById('codeInput').value;
  const loading = document.getElementById('loading');
  
  loading.style.display = 'block';
  
  try {
    var response = await callAzureFunction(codeInput);

    if ( codeInput === 'testuserone' || codeInput === 'testusertwo' || (response != null && response.isConfirmed)) {
      if (codeInput === 'testuserone'){
        response = {
          name: 'Corey',
          email: 'coreyhom@test.com',
          hasOne: true,
          description: "We are so excited to have you at our wedding! We hope you can make it!",
          hasCeremony: true,
          hasReception: true
        };
      }

      if (codeInput === 'testusertwo'){
        response = {
          name: 'Corey',
          email: 'coreyhom@test.com',
          hasOne: false,
          description: "",
          hasCeremony: false,
          hasReception: true
        };
      }

      document.getElementById('loginSection').style.display = 'none';
      const content = document.getElementById('content');
      content.style.display = 'block';

      setUserInfo(response);

      localStorage.setItem(loginCookie, expirationTime);
      loadDynamicText();
      setTimeout(() => {
        content.classList.add('fade-in');
      }, 3);
    } else {
      alert("Incorrect code. Please try again or contact Corey! Might be a mistake on my part too. :)");
    }
  } catch (error) {
    console.error("Error during code check:", error);
    alert("An error occurred. Please try again later.");
  } finally {
    loading.style.display = 'none';
  }
}


window.onload = function() {
  const loader = document.getElementById("loader");
  const loginSection = document.getElementById("loginSection");
  const content = document.getElementById("content");

  loginSection.style.display = "none"; 
  loader.style.display = "block";

  const expirationTime = localStorage.getItem(loginCookie);
  const isLoggedIn = expirationTime != null && Date.now() < parseInt(expirationTime, 10);

  if (isLoggedIn) {
    loader.style.display = "none";
    loginSection.style.display = "none";
    content.style.display = "block";
    content.classList.add('fade-in');
    if (window.location.pathname.endsWith("index.html") || window.location.pathname === "/" || window.location.pathname === "") {
      loadDynamicText();
    }
  } else {
    loader.style.display = "none";
    loginSection.style.display = "block"; 
    content.style.display = "none";
  }
};

var todo = 'api123';